apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: solar-code
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: solar-code
    spec:
      containers:
      - name: solar-code
        image: solar-code:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: solar-code
spec:
  type: NodePort
  ports:
    - nodePort: 31001
      name: http
      port: 4000
      protocol: TCP
  selector:
    app: solar-code
---
kind: Service
apiVersion: v1
metadata:
  name: minikube-host
spec:
  type: ExternalName
  externalName: solarcode.host
